local B, C, L, DB = unpack(select(2, ...))
local cr, cg, cb = DB.cc.r, DB.cc.g, DB.cc.b

-- top infobar 顶部信息条背景
local Tinfobar = CreateFrame("Frame", nil, UIParent)
Tinfobar:SetPoint("TOPLEFT", UIParent, "TOPLEFT", 0, -3)
B.CreateGF(Tinfobar, 600, 15, "Horizontal", 0, 0, 0, 0.5, 0)
local Tinfobar1 = CreateFrame("Frame", nil, Tinfobar)
Tinfobar1:SetPoint("BOTTOM", Tinfobar, "TOP")
B.CreateGF(Tinfobar1, 600, 1, "Horizontal", cr, cg, cb, 0.7, 0)
local Tinfobar2 = CreateFrame("Frame", nil, Tinfobar)
Tinfobar2:SetPoint("TOP", Tinfobar, "BOTTOM")
B.CreateGF(Tinfobar2, 600, 1, "Horizontal", cr, cg, cb, 0.7, 0)

-- bottomleft infobar 左下角信息条背景
local Linfobar = CreateFrame("Frame", nil, UIParent)
Linfobar:SetPoint("BOTTOMLEFT", UIParent, "BOTTOMLEFT", 0, 3)
B.CreateGF(Linfobar, 450, 220, "Horizontal", 0, 0, 0, 0.6, 0)
local Linfobar1 = CreateFrame("Frame", nil, Linfobar)
Linfobar1:SetPoint("BOTTOM", Linfobar, "TOP")
B.CreateGF(Linfobar1, 450, 1, "Horizontal", cr, cg, cb, 0.7, 0)
local Linfobar2 = CreateFrame("Frame", nil, Linfobar)
Linfobar2:SetPoint("BOTTOM", Linfobar, "BOTTOM", 0, 18)
B.CreateGF(Linfobar2, 450, 1, "Horizontal", cr, cg, cb, 0.7, 0)
local Linfobar3 = CreateFrame("Frame", nil, Linfobar)
Linfobar3:SetPoint("TOP", Linfobar, "BOTTOM")
B.CreateGF(Linfobar3, 450, 1, "Horizontal", cr, cg, cb, 0.7, 0)

-- bottomright infobar 聊天背景
local Rinfobar = CreateFrame("Frame", nil, UIParent)
Rinfobar:SetPoint("BOTTOMRIGHT", UIParent, "BOTTOMRIGHT", 0, 3)
B.CreateGF(Rinfobar, 450, 18, "Horizontal", 0, 0, 0, 0, 0.6)
local Rinfobar1 = CreateFrame("Frame", nil, Rinfobar)
Rinfobar1:SetPoint("BOTTOM", Rinfobar, "TOP")
B.CreateGF(Rinfobar1, 450, 1, "Horizontal", cr, cg, cb, 0, 0.6)
local Rinfobar2 = CreateFrame("Frame", nil, Rinfobar)
Rinfobar2:SetPoint("TOP", Rinfobar, "BOTTOM")
B.CreateGF(Rinfobar2, 450, 1, "Horizontal", cr, cg, cb, 0, 0.6)

-- micromenu 微型菜单背景
local mmbottomL = CreateFrame("Frame", nil, UIParent)
mmbottomL:SetPoint("BOTTOM", UIParent, "BOTTOM", -126, 2)
B.CreateGF(mmbottomL, 250, 1, "Horizontal", cr, cg, cb, 0, 0.7)
local mmbottomR = CreateFrame("Frame", nil, UIParent)
mmbottomR:SetPoint("BOTTOM", UIParent, "BOTTOM", 126, 2)
B.CreateGF(mmbottomR, 250, 1, "Horizontal", cr, cg, cb, 0.7, 0)

local mmtopL = CreateFrame("Frame", nil, UIParent)
mmtopL:SetPoint("BOTTOM", UIParent, "BOTTOM", -161, 23)
B.CreateGF(mmtopL, 320, 1, "Horizontal", cr, cg, cb, 0, 0.7)
local mmtopR = CreateFrame("Frame", nil, UIParent)
mmtopR:SetPoint("BOTTOM", UIParent, "BOTTOM", 161, 23)
B.CreateGF(mmtopR, 320, 1, "Horizontal", cr, cg, cb, 0.7, 0)

-- main actionbar 主动作条背景
local MactionbarL = CreateFrame("Frame", nil, UIParent)
MactionbarL:SetPoint("BOTTOM", UIParent, "BOTTOM", -161, 3)
B.CreateGF(MactionbarL, 320, 98, "Horizontal", 0, 0, 0, 0, 0.5)
local MactionbarL1 = CreateFrame("Frame", nil, MactionbarL)
MactionbarL1:SetPoint("BOTTOM", MactionbarL, "TOP")
B.CreateGF(MactionbarL1, 320, 1, "Horizontal", cr, cg, cb, 0, 0.7)
RegisterStateDriver(MactionbarL, "visibility", "[petbattle][overridebar][vehicleui][possessbar,@vehicle,exists] hide; show")

local MactionbarR = CreateFrame("Frame", nil, UIParent)
MactionbarR:SetPoint("BOTTOM", UIParent, "BOTTOM", 161, 3)
B.CreateGF(MactionbarR, 320, 98, "Horizontal", 0, 0, 0, 0.5, 0)
local MactionbarR1 = CreateFrame("Frame", nil, MactionbarL)
MactionbarR1:SetPoint("BOTTOM", MactionbarR, "TOP")
B.CreateGF(MactionbarR1, 320, 1, "Horizontal", cr, cg, cb, 0.7, 0)
RegisterStateDriver(MactionbarR, "visibility", "[petbattle][overridebar][vehicleui][possessbar,@vehicle,exists] hide; show")

-- Overridebar 载具条背景
local OverbarL = CreateFrame("Frame", nil, UIParent)
OverbarL:SetPoint("BOTTOM", UIParent, "BOTTOM", -101, 3)
B.CreateGF(OverbarL, 200, 60, "Horizontal", 0, 0, 0, 0, 0.5)
local OverbarL1 = CreateFrame("Frame", nil, OverbarL)
OverbarL1:SetPoint("BOTTOM", OverbarL, "TOP")
B.CreateGF(OverbarL1, 200, 1, "Horizontal", cr, cg, cb, 0, 0.7)
RegisterStateDriver(OverbarL, "visibility", "[petbattle]hide; [overridebar][vehicleui][possessbar,@vehicle,exists] show; hide")

local OverbarR = CreateFrame("Frame", nil, UIParent)
OverbarR:SetPoint("BOTTOM", UIParent, "BOTTOM", 101, 3)
B.CreateGF(OverbarR, 200, 60, "Horizontal", 0, 0, 0, 0.5, 0)
local OverbarR1 = CreateFrame("Frame", nil, OverbarL)
OverbarR1:SetPoint("BOTTOM", OverbarR, "TOP")
B.CreateGF(OverbarR1, 200, 1, "Horizontal", cr, cg, cb, 0.7, 0)
RegisterStateDriver(OverbarR, "visibility", "[petbattle]hide; [overridebar][vehicleui][possessbar,@vehicle,exists] show; hide")